[versions]
# project modules version
p-root = "1.0.0-dev"
p-lavender-api = "1.0.0-dev"
p-lavsource-spring-boot-starter = "1.0.0-dev"
p-lavsource-core-android = "1.0.0-dev"

# gradle plugins version
gp-honoka-basic = "1.0.3"

# dependencies version
d-kotlin = "2.2.0"
d-kotlin-coroutines = "1.10.2"
d-honoka-kotlin-utils = "1.1.4-dev"
d-lavender-api = "1.0.0-dev"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "d-kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "d-kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "d-kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "d-kotlin" }
honoka-basic = { id = "de.honoka.gradle.plugin.basic", version.ref = "gp-honoka-basic" }

[libraries]
honoka-kotlin-utils = { module = "de.honoka.sdk:honoka-kotlin-utils", version.ref = "d-honoka-kotlin-utils" }
lavender-api = { module = "de.honoka.lavender:lavender-api", version.ref = "d-lavender-api" }
