[versions]
# dependencies version
d-spring-boot = "3.5.4"
d-honoka-spring-boot-starter = "1.0.4-dev"

[libraries]
honoka-spring-boot-starter = { module = "de.honoka.sdk:honoka-spring-boot-starter", version.ref = "d-honoka-spring-boot-starter" }
